name: Pub

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Publish to Pub.dev
        if: "contains(github.event.head_commit.message, '[publish]')"
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}          
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}